# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('c3p-example', ['c3p'])
    # obj.source = 'c3p-simple-test.cc'
    # obj.source = 'c3p-test.cc'
